In [1]:
import numpy as np
import matplotlib.pyplot as plt
keys=np.loadtxt("KeyboardData1.csv",dtype='str',delimiter=',')
labels = keys[1:,0]
keys=keys[:,1:] # On retire la premiere colonne
varbs=keys[0,:] #nom des variables
X=keys[1:,:].astype(float)

In [2]:
print(X)
print(labels)

[[0.1491 0.2488 0.1069 ... 0.1338 0.2171 0.0742]
 [0.1111 0.234  0.0694 ... 0.0839 0.1917 0.0747]
 [0.1328 0.0744 0.0731 ... 0.1085 0.1762 0.0945]
 ...
 [0.0939 0.025  0.1008 ... 0.1034 0.0983 0.0905]
 [0.0923 0.0371 0.0913 ... 0.0979 0.0938 0.0931]
 [0.0596 0.0714 0.0992 ... 0.0807 0.1186 0.1018]]
['2' '2' '2' ... '57' '57' '57']


### Analyse discriminante linéaire 

In [33]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.metrics import confusion_matrix

lda = LinearDiscriminantAnalysis()
lda.fit(X,labels)
yhat = lda.predict(X)
errl=sum(labels!=yhat)/len(labels)
print("Taux d'erreur: ",round(errl,4))

Taux d'erreur:  0.22


In [34]:
print(yhat)

['2' '31' '2' ... '57' '26' '55']


### Avec validation croisée
On fait ici la validation croisée la plus simple en coupant l'ensemble en deux


In [35]:
y = labels
ntest=np.floor(len(y)/2).astype(int)
per=np.random.permutation(len(y))
lt,la=per[:ntest], per[ntest:]
Xa,Xt=X[la,:],X[lt,:] 
ya,yt=y[la],y[lt] 
lda.fit(Xa,ya)
yhat = lda.predict(Xt)      
errl=sum(yt!=yhat)/len(yt)
print("Taux d'erreur: ",round(errl,3))

Taux d'erreur:  0.228


### Moyenne de N tirage

In [37]:
N = 10
errl=0
for i in range(N):
    ntest=np.floor(len(y)/2).astype(int)
    per=np.random.permutation(len(y))
    lt,la=per[:ntest], per[ntest:]
    Xa,Xt=X[la,:],X[lt,:] 
    ya,yt=y[la],y[lt] 
    lda.fit(Xa,ya)
    yhat = lda.predict(Xt)      
    errl+=sum(yt!=yhat)/len(yt)
errl = errl/N
print(round(errl,4))

0.2263


### Analyse discriminante quadratique 

In [99]:
from sklearn.discriminant_analysis import QuadraticDiscriminantAnalysis

lda = QuadraticDiscriminantAnalysis()
lda.fit(X,y)
yhat = lda.predict(X)
errl=sum(y!=yhat)/len(y)
print("Taux d'erreur: ",round(errl,3))
conf =  confusion_matrix(y,yhat)
print("Matrice de confusion (sans validation croisée)\n")
conf=conf.astype(str)
conf=np.append(np.array(['y=0  ','y=1  '])[:,np.newaxis],conf,axis=1)
conf=np.append(np.array(['   ','yh=0 ','yh=1'])[np.newaxis,:],conf,axis=0)
print('\n'.join([''.join(['{:4}'.format(item) for item in row]) 
      for row in conf]))

Taux d'erreur:  0.242
Matrice de confusion (sans validation croisée)

    yh=0 yh=1
y=0  257 45  
y=1  67  93  


In [109]:
ntest=np.floor(len(y)/5).astype(int)
per=np.random.permutation(len(y))
lt,la=per[:ntest], per[ntest:]
Xa,Xt=X[la,:],X[lt,:] 
ya,yt=y[la],y[lt] 
lda.fit(Xa,ya)
yhat = lda.predict(Xt)      
errl=sum(yt!=yhat)/len(yt)
print("Taux d'erreur: ",round(errl,3))

Taux d'erreur:  0.337
